## Import Library

In [11]:
!pip install opencv-python
!pip install numpy
!pip install matplotlib

In [12]:
import cv2
import numpy as np

ModuleNotFoundError: No module named 'cv2'

## Membaca Citra

In [2]:
citra = cv2.imread('orange2.jpg')

In [3]:
cv2.imshow("citra asli", citra)
cv2.waitKey()
cv2.destroyAllWindows()

## Dimensi Citra

In [6]:
print(citra.shape)
print(citra.dtype)

(398, 600, 3)
uint8


## Splitting Citra RGB

In [4]:
b = citra [:,:,0]
g = citra [:,:,1]
r = citra [:,:,2]

In [5]:
panjang = len(citra)
lebar = len(citra[0])

citra_gray = np.zeros ((panjang,lebar))

for i in range (panjang):#0 - 544
    for j in range (lebar): #0 - 960
        citra_gray[i,j] = 0.2989 * r[i,j] + 0.587 * g[i,j] + 0.1141 * b [i,j] # merah - 29,89% ; hijau - 58,7% ; biru - 11,41%
        
citra_gray = citra_gray.astype(np.uint8)
cv2.imshow("citra grayscale", citra_gray)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
print(citra)

[[[ 16  13   9]
  [ 16  13   9]
  [ 14  12  11]
  ...
  [ 23  83 125]
  [ 20  56  92]
  [  0  13  47]]

 [[ 17  14  10]
  [ 15  14  10]
  [ 15  13  12]
  ...
  [ 27  87 129]
  [ 25  62 100]
  [  0  18  52]]

 [[ 15  13  12]
  [ 15  13  12]
  [ 15  13  13]
  ...
  [ 26  90 131]
  [ 25  67 104]
  [  0  24  59]]

 ...

 [[  0  67  92]
  [  0  67  91]
  [  0  65  90]
  ...
  [  2  90 180]
  [  0  87 179]
  [  0  87 179]]

 [[  0  66  89]
  [  0  66  89]
  [  0  66  89]
  ...
  [  1  91 180]
  [  1  91 180]
  [  2  92 181]]

 [[  0  66  89]
  [  0  66  89]
  [  0  66  89]
  ...
  [  1  91 180]
  [  2  92 181]
  [  4  94 183]]]


## Graysclae to Binary

In [17]:
panjang = len(citra)
lebar = len(citra[0])

ambang = 90

citra_biner = np.zeros((panjang,lebar))

for i in range (panjang):#0 - 544
    for j in range (lebar): #0 - 960
        if citra_gray[i,j] >= ambang:
            citra_biner[i,j] = 1 #putih 255
        else:
            citra_biner[i,j] = 0 #hitam 0
        
cv2.imshow("citra binary", citra_biner)
cv2.waitKey()
cv2.destroyAllWindows()

In [12]:
print(citra_biner)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]]
